[package]
name = "bevy_ecs_tilemap"
description = "A tilemap rendering plugin for bevy which is more ECS friendly by having an entity per tile."
version = "0.4.0"
authors = ["John Mitchell"]
homepage = "https://github.com/StarArawn/bevy_ecs_tilemap"
repository = "https://github.com/StarArawn/bevy_ecs_tilemap"
license-file = "LICENSE"
edition = "2018"
exclude = [
    "assets/*",
    "screenshots/*",
]

[features]
default = ["ldtk"]
ldtk = ["anyhow", "ldtk_rust", "serde_json"]

[dependencies]
anyhow = { version = "1.0", optional = true }
bevy = "0.5"
futures-util = "0.3"
ldtk_rust = { version = "0.5", optional = true }
morton-encoding = "2.0"
log = "0.4"
serde_json = { version = "1.0", optional = true }

[dev-dependencies]
rand = "0.8"
env_logger = "0.8"