[package]
name = "bevy_ecs_tilemap"
description = "A tilemap rendering plugin for bevy which is more ECS friendly by having an entity per tile."
version = "0.4.0"
authors = ["John Mitchell"]
homepage = "https://github.com/StarArawn/bevy_ecs_tilemap"
repository = "https://github.com/StarArawn/bevy_ecs_tilemap"
license-file = "LICENSE"
edition = "2021"
exclude = ["assets/*", "screenshots/*"]

[features]
default = []

[dependencies]
bevy = { git = "https://github.com/cart/bevy", rev = "911f69ce3a5394e73f6a4bed3a6f5922d1205d37" }
crevice = { git = "https://github.com/cart/bevy", rev = "911f69ce3a5394e73f6a4bed3a6f5922d1205d37" }
morton-encoding = "2.0"
log = "0.4"
regex = "1.5.4"
bytemuck = "1.7.2"

[dev-dependencies]
anyhow = { version = "1.0" }
bevy = { git = "https://github.com/cart/bevy", rev = "911f69ce3a5394e73f6a4bed3a6f5922d1205d37", default-features = false }
ldtk_rust = { version = "0.5" }
rand = "0.8"
env_logger = "0.9"
serde_json = { version = "1.0" }
tiled = { version = "0.9", default-features = false }

[[example]]
name = "ldtk"
path = "examples/ldtk/ldtk_usage.rs"

[[example]]
name = "tiled"
path = "examples/tiled/tiled_usage.rs"

[[example]]
name = "tiled_rotate"
path = "examples/tiled/tiled_rotate.rs"
