[package]
name = "bevy_ecs_tilemap"
description = "A tilemap rendering plugin for bevy which is more ECS friendly by having an entity per tile."
version = "0.1.0"
authors = ["John Mitchell"]
homepage = "https://github.com/StarArawn/bevy_ecs_tilemap"
repository = "https://github.com/StarArawn/bevy_ecs_tilemap"
license-file = "LICENSE"
edition = "2018"
exclude = [
    "assets/*",
]

[dependencies]
bevy = "0.5"
log = "0.4"
dyn-clone = "1.0"

[dev-dependencies]
rand = "0.8"
env_logger = "0.8"